graph TD
    A[사용자 인터페이스] --> B[브라우저2 엔진]
    B --> C[렌더링 엔진]
    B --> G[네트워크 레이어]
    C --> D[자료 스토리지]
    C --> E[자바스크립트 인터프리터]
    C --> F[UI 백엔드]

    G --> C
    D --> C
    E --> C
    F --> A
